import type { VideoFormula } from '../types/project';

export const mrbeastFormula: VideoFormula = {
  id: 'mrbeast-viral',
  name: 'MrBeast Viral',
  description:
    'High-energy format inspired by top YouTube creators. Fast cuts, dramatic hooks, constant re-engagement, and an abrupt ending that leaves viewers wanting more.',
  author: 'Remotion Studio',
  tags: ['youtube', 'viral', 'high-energy', 'fast-paced'],
  targetDuration: 180,
  fps: 30,
  resolution: [1920, 1080],
  defaultTransition: { type: 'zoom', duration: 0.3 },
  segments: [
    {
      label: 'Cold Open Hook',
      purpose: 'hook',
      duration: 3,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 30, shotDuration: 2 },
        transition: 'zoom',
        transitionDuration: 0.2,
        colorMood: 'vibrant',
        energy: 10,
        textOverlayHint: 'WATCH THIS',
        kenBurns: 'zoom-in',
        audioMood: 'intense',
        sfxIntensity: 9,
      },
      promptHint:
        'The most dramatic visual moment — show the stakes immediately',
    },
    {
      label: 'Payoff Tease',
      purpose: 'hook',
      duration: 2,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 40, shotDuration: 1.5 },
        transition: 'zoom',
        transitionDuration: 0.15,
        colorMood: 'neon',
        energy: 10,
        textOverlayHint: 'BUT FIRST...',
        audioMood: 'intense',
        sfxIntensity: 10,
      },
      promptHint: "Flash-forward to the climax — what's at stake",
    },
    {
      label: 'Setup / Context',
      purpose: 'setup',
      duration: 10,
      defaultSceneType: 'ai-image',
      style: {
        pacing: { cutsPerMin: 12, shotDuration: 5 },
        transition: 'crossfade',
        transitionDuration: 0.5,
        colorMood: 'vibrant',
        energy: 7,
        kenBurns: 'zoom-in',
        audioMood: 'building',
        sfxIntensity: 5,
      },
      promptHint: 'Establish the premise — what, where, why',
    },
    {
      label: 'Subject Introduction',
      purpose: 'setup',
      duration: 15,
      defaultSceneType: 'ai-image',
      style: {
        pacing: { cutsPerMin: 10, shotDuration: 6 },
        transition: 'slide',
        transitionDuration: 0.4,
        colorMood: 'warm',
        energy: 8,
        kenBurns: 'pan-right',
        audioMood: 'building',
        sfxIntensity: 4,
      },
      promptHint:
        'Introduce the key subjects — people, products, or ideas',
    },
    {
      label: 'Early Progression',
      purpose: 'progression',
      duration: 30,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 8, shotDuration: 7 },
        transition: 'crossfade',
        transitionDuration: 0.5,
        colorMood: 'vibrant',
        energy: 6,
        audioMood: 'building',
        sfxIntensity: 5,
      },
      promptHint:
        'First phase of the journey — initial action, early results',
    },
    {
      label: 'Escalation',
      purpose: 'progression',
      duration: 30,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 12, shotDuration: 5 },
        transition: 'wipe',
        transitionDuration: 0.4,
        colorMood: 'warm',
        energy: 7,
        audioMood: 'suspense',
        sfxIntensity: 6,
      },
      promptHint:
        'Things get more intense — higher stakes, complications',
    },
    {
      label: 'Twist / Re-engage',
      purpose: 're-engage',
      duration: 10,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 20, shotDuration: 3 },
        transition: 'iris',
        transitionDuration: 0.3,
        colorMood: 'danger-red',
        energy: 9,
        textOverlayHint: 'PLOT TWIST',
        audioMood: 'chaotic',
        sfxIntensity: 8,
      },
      promptHint:
        'Unexpected turn — new information, plot twist, surprise',
    },
    {
      label: 'Deep Middle',
      purpose: 'middle',
      duration: 30,
      defaultSceneType: 'ai-image',
      style: {
        pacing: { cutsPerMin: 6, shotDuration: 10 },
        transition: 'crossfade',
        transitionDuration: 0.8,
        colorMood: 'cool',
        energy: 5,
        kenBurns: 'zoom-in',
        audioMood: 'calm',
        sfxIntensity: 2,
      },
      promptHint:
        'Emotional depth — closeups, personal moments, reflection',
    },
    {
      label: 'Energy Spike',
      purpose: 're-engage',
      duration: 10,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 25, shotDuration: 2.5 },
        transition: 'zoom',
        transitionDuration: 0.2,
        colorMood: 'neon',
        energy: 9,
        textOverlayHint: 'WAIT FOR IT',
        audioMood: 'intense',
        sfxIntensity: 9,
      },
      promptHint:
        'Re-energize — dramatic reveal, turning point',
    },
    {
      label: 'Climax',
      purpose: 'climax',
      duration: 30,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 30, shotDuration: 2 },
        transition: 'zoom',
        transitionDuration: 0.15,
        colorMood: 'danger-red',
        energy: 10,
        textOverlayHint: 'THE MOMENT',
        audioMood: 'triumphant',
        sfxIntensity: 10,
      },
      promptHint:
        'Peak moment — fastest cuts, maximum tension, resolution',
    },
    {
      label: 'Abrupt End',
      purpose: 'end',
      duration: 10,
      defaultSceneType: 'ai-video',
      style: {
        pacing: { cutsPerMin: 20, shotDuration: 3 },
        transition: 'fade',
        transitionDuration: 0.3,
        colorMood: 'vibrant',
        energy: 10,
        textOverlayHint: 'SUBSCRIBE',
        audioMood: 'intense',
        sfxIntensity: 8,
      },
      promptHint:
        'End on the highest note — no wind-down, just stop',
    },
  ],
};
